Views
skvortsovvg/TestGuru pull request #11
Opened 2022-05-16 14:13 UTC by skvortsovvg

2022-05-16 16:58 UTC, BubuntuClu requested changes

2022-05-16 16:58 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
надо вернуть `new` как было. заменив на `create` ты добавил лишний запрос в БД, так как под капотом `create` делает сохранение в БД. таким образом ты пытаешься два раза в БД сохранить

2022-05-16 16:58 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author.strip}/#{repo.strip}"
возвращай тут хэлпер `link_to` сразу, чтобы не прописывать всю разметку во вьюхе. да и метод без этого выглядит странно, просто собирает строку

2022-05-16 16:58 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    # "https://github.com/"skvortsovvg/TestGuru
строка ниже слишком простая, чтобы она требовала комментариев

2022-05-16 16:58 UTC, BubuntuClu commented on app/helpers/tests_helper.rb
> +  def question_header(question, test)
можно уменьшить количество аргументов метода на один, ты ведь можешь из вопроса получить тест по ассоциации

2022-05-16 16:58 UTC, BubuntuClu commented on app/views/questions/edit.html.erb
> +<%= form_with model: @question do |form| %>
у тебя общий код во вьюхах `new` и `edit` должен быть. разницы между ними никакой. надо вынести в форму редактирования в паршиал. во вьюхах `new` и `edit`  просто вызывать рендер паршиала

2022-05-17 11:09 UTC, skvortsovvg commented on app/controllers/questions_controller.rb
> +    question = @test.questions.create(question_params)
+

2022-05-17 11:11 UTC, skvortsovvg commented on app/helpers/application_helper.rb
> +    "https://github.com/#{author.strip}/#{repo.strip}"
+

2022-05-17 11:11 UTC, skvortsovvg commented on app/helpers/application_helper.rb
> +    # "https://github.com/"skvortsovvg/TestGuru
+

2022-05-17 11:17 UTC, skvortsovvg commented on app/helpers/tests_helper.rb
> +  def question_header(question, test)
+

2022-05-17 11:17 UTC, skvortsovvg commented on app/views/questions/edit.html.erb
> +<%= form_with model: @question do |form| %>
+

2022-05-25 09:37 UTC, merged