Application
skvortsovvg/TestGuru pull request #12
Opened 2022-06-07 14:51 UTC by skvortsovvg

2022-06-07 18:05 UTC, BubuntuClu requested changes

2022-06-07 18:05 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создавай ответ через ассоциацию вопроса

2022-06-07 18:05 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    respond_to do |format|
у тебя подразумевается только один формат, нет смысла делать этот блок. + ты формат никак не проверешь чтобы делать разные ответы для разных форматов

2022-06-07 18:05 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    respond_to do |format|
аналогично и тут. нужно убрать везде эти блоки, так как ты не отдаешь другие форматы

2022-06-07 18:05 UTC, BubuntuClu commented on app/controllers/results_controller.rb
> +    if params[:answer_id].present?
если ответов нет, то что происходит? надо же как-то уведомить пользователя о том что случилось.
как вариант ничего не делать, а считать ответы с пустыми данными

2022-06-07 18:05 UTC, BubuntuClu commented on app/controllers/results_controller.rb
> +    if params[:answer_id].present?
вложенные `if'ы` это не очень хорошо. попробуй переписать код, чтобы их не было. как вариант `return if params[:answer_id].blank?` а дальше твой обычный иф. но это просто про то как можно избавляться от вложенных конструкций. пользователю все равно надо что-то сказать если ты хочешь такую логику кода оставлять

2022-06-07 18:05 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @user.tests << @test if @user.test_passing(@test).nil?
зачем нужна проверка? чет не уловил смысла

2022-06-07 18:05 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    redirect_to @user.test_passing(@test)
кажется тут должно быть `@user.results(@test)`

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +  belongs_to :current_qst, class_name: "Question", optional: true
не скупись на полный нейминг абстракций. тебя в месте никто не ограничивает. назови полностью `current_question`

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +    if current_qst.answers.find(answer_id).correct then
`then` в руби не пишется

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +  def resume
`result` больше подходит по смыслу

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +    self.current_qst = test.questions.where('id > ?', current_qst.id).order(:id).first if test.present? && !current_qst.nil?
`!current_qst.nil?` у тебя есть метод `compelted?` который делает эту проверку. используй его вместо дублирования кода

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +    self.current_qst = test.questions.first if test.present? && current_qst.nil?
`current_qst.nil?` у тебя есть метод `compelted?` который делает эту проверку. используй его вместо дублирования кода

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +  def before_create_set_qst()
скобки не пишутся если параметров нет

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +      self.total += 1
что за тотал? звучит как общее количество. а общее количество чего?

2022-06-07 18:05 UTC, BubuntuClu commented on app/models/result.rb
> +    if current_qst.answers.find(answer_id).correct then
ответов может быть много, мне кажется твой вариант проверки этого не учитывает

2022-06-07 18:05 UTC, BubuntuClu commented on app/views/results/finish.html.erb
> +<% if @result.resume >= 85 %>
85 это магическое число, если не знать контекста. надо вынести его в константу в модель и обозвать понятно

2022-06-07 18:05 UTC, BubuntuClu commented on app/views/results/finish.html.erb
> +<% if @result.resume >= 85 %>
`if @result.resume >= 85` эту проверку можно сделать методом модели `@result.success?`

2022-06-07 18:05 UTC, BubuntuClu commented on db/migrate/20220602140638_add_current_question_and_right_questions_to_result.rb
> +    add_reference(:results, :current_qst, optional: true, foreign_key: { to_table: 'questions' })
предлагаю `current_question` и `correct_questions` вместо текущих названий столбцов использовать

2022-06-08 10:12 UTC, skvortsovvg commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
+

2022-06-08 10:12 UTC, skvortsovvg commented on app/controllers/answers_controller.rb
> +    respond_to do |format|
+

2022-06-08 10:12 UTC, skvortsovvg commented on app/controllers/answers_controller.rb
> +    respond_to do |format|
+

2022-06-08 10:15 UTC, skvortsovvg commented on app/controllers/results_controller.rb
> +    if params[:answer_id].present?
Если ответ не выбран, то ничего не происходит, перересовывается та же страница. Пользователь ведь проходит тест, тут очевидно, что нужно выбрать какой-то вариант ответа. Убрал вложенный if, сделал как ты посоветовал через return.

2022-06-08 10:17 UTC, skvortsovvg commented on app/controllers/tests_controller.rb
> +    @user.tests << @test if @user.test_passing(@test).nil?
Смысл проверки в том, чтобы учесть существующие незавершенные тестирования. Если такие есть, то ранее прераванное тестирование будет продолжено. Если все тестирования завершены, то будет запущен новый тест.

2022-06-08 10:18 UTC, skvortsovvg commented on app/controllers/tests_controller.rb
> +    redirect_to @user.test_passing(@test)
test_passing здесь это функция, которая подбирает прохождение теста

2022-06-08 10:20 UTC, skvortsovvg commented on app/models/result.rb
> +  belongs_to :current_qst, class_name: "Question", optional: true
+

2022-06-08 10:21 UTC, skvortsovvg commented on app/models/result.rb
> +    if current_qst.answers.find(answer_id).correct then
У меня там переключатель, если ответов несколько, будет соответствующий вариант. Then убрал.

2022-06-08 10:21 UTC, skvortsovvg commented on app/models/result.rb
> +  def resume
+

2022-06-08 10:22 UTC, skvortsovvg commented on app/models/result.rb
> +    self.current_qst = test.questions.where('id > ?', current_qst.id).order(:id).first if test.present? && !current_qst.nil?
+

2022-06-08 10:23 UTC, skvortsovvg commented on app/models/result.rb
> +    self.current_qst = test.questions.first if test.present? && current_qst.nil?
+

2022-06-08 10:23 UTC, skvortsovvg commented on app/models/result.rb
> +  def before_create_set_qst()
+

2022-06-08 10:25 UTC, skvortsovvg commented on app/models/result.rb
> +      self.total += 1
Сделал correct_questions

2022-06-08 10:27 UTC, skvortsovvg commented on db/migrate/20220602140638_add_current_question_and_right_questions_to_result.rb
> +    add_reference(:results, :current_qst, optional: true, foreign_key: { to_table: 'questions' })
+

2022-06-08 10:27 UTC, skvortsovvg commented on app/views/results/finish.html.erb
> +<% if @result.resume >= 85 %>
+

2022-06-08 17:39 UTC, BubuntuClu commented on app/controllers/results_controller.rb
> +    if params[:answer_id].present?
ладно, до сообщений еще дойдем, там увидишь как можно оповестить пользователя

2022-06-08 17:40 UTC, BubuntuClu commented on app/models/result.rb
> +    result >= 85
значение в константу вынеси, чтобы понимать что обозначает это число

2022-06-08 18:13 UTC, skvortsovvg commented on app/models/result.rb
> +    result >= 85
+

2022-06-08 18:13 UTC, merged