GitHub api
skvortsovvg/TestGuru pull request #17
Opened 2022-06-29 15:23 UTC by skvortsovvg

2022-06-29 18:47 UTC, BubuntuClu requested changes

2022-06-29 18:47 UTC, BubuntuClu commented on app/controllers/admin/gists_controller.rb
> +  def index
тут какая-то реализация будет?

2022-06-29 18:47 UTC, BubuntuClu commented on app/models/gist.rb
> +  validates :question, presence: true, uniqueness: { scope: :author }
а зачем такое ограничение?

2022-06-29 18:47 UTC, BubuntuClu commented on app/models/gist.rb
> +  validates :id, presence: true, uniqueness: true
id это первичный ключ таблицы. он по умолчанию уникальный

2022-06-29 18:47 UTC, BubuntuClu commented on app/views/admin/gists/_gist.html.erb
> +  <td><%= link_to gist.id, "https://gist.github.com/" + gist.id, overflow: 'hidden', target: '_blanck'  %></td>
_blanck - опечатка

2022-06-29 18:47 UTC, BubuntuClu commented on app/views/admin/gists/index.html.erb
> +      <%= render Gist.all.order(:created_at) %>
запросов во вьюхе не должно быть. получение данных происходит в контроллере

2022-06-29 18:47 UTC, BubuntuClu commented on config/routes.rb
> +        post  :gist, as: 'new_gist'
new_gist - это же обычный `create`. зачем ему кастомное имя? не по REST

2022-06-29 18:47 UTC, BubuntuClu commented on db/migrate/20220628120637_create_gists.rb
> +      t.id :string, limit: 50
не стоит так делать. оставляй этот столбец всегда интовым и не вноси изменения, без особой надобности

2022-06-29 18:47 UTC, BubuntuClu commented on app/controllers/admin/gists_controller.rb
> +  def index
увидел, она во вьюхе, что неправильно

2022-06-29 18:47 UTC, BubuntuClu commented on app/services/GistQuestionService.rb
> +    @client = Octokit::Client.new(:access_token => ENV['GITHUB_GIST_TOKEN'])
`access_token: ENV['GITHUB_GIST_TOKEN']`

2022-06-29 18:47 UTC, BubuntuClu commented on app/services/GistQuestionService.rb
> +    gist = Gist.new(
раньше времени создаешь гист у себя. ответ от сервиса может быть не успех, тогда зря инициализировал и память выделял

2022-06-29 18:47 UTC, BubuntuClu commented on app/services/GistQuestionService.rb
> +      if gist.save
логика внутри ифа это уже что-то за пределами обязанности сервиса. стоит вынести это в контроллер. 
сервис просто делает запрос в гистхаб и может сказать успешно он его сделал или нет.
а на уровне выше ты оперируешь этими метода

```
service = GistService.new
result = service.call
if service.succes?
   create gist locally
   message with success
else
   message with failure
end
```

как-то так будет выглядеть контроллер

2022-06-29 18:47 UTC, BubuntuClu commented on app/services/GistQuestionService.rb
> +    rescue => details
логика построенная на отлове ошибок, не очень хорошая практика

2022-06-30 06:48 UTC, skvortsovvg commented on app/models/gist.rb
> +  validates :question, presence: true, uniqueness: { scope: :author }
ну допольнительно, чтобы обеспечить уникальность связки вопрос-автор. если gist от этого юзера этого автора уже создан, он отобразится на форме вопроса

2022-06-30 06:50 UTC, skvortsovvg commented on db/migrate/20220628120637_create_gists.rb
> +      t.id :string, limit: 50
я подумал, что id gitа уникальные, поэтому можно на них полагаться при хранении

2022-06-30 06:52 UTC, skvortsovvg commented on app/models/gist.rb
> +  validates :id, presence: true, uniqueness: true
+

2022-06-30 06:52 UTC, skvortsovvg commented on app/views/admin/gists/_gist.html.erb
> +  <td><%= link_to gist.id, "https://gist.github.com/" + gist.id, overflow: 'hidden', target: '_blanck'  %></td>
+

2022-06-30 06:53 UTC, skvortsovvg commented on app/views/admin/gists/index.html.erb
> +      <%= render Gist.all.order(:created_at) %>
+

2022-06-30 06:54 UTC, skvortsovvg commented on app/services/GistQuestionService.rb
> +    @client = Octokit::Client.new(:access_token => ENV['GITHUB_GIST_TOKEN'])
+

2022-06-30 06:56 UTC, skvortsovvg commented on app/services/GistQuestionService.rb
> +    gist = Gist.new(
я здесь сам объект использую как структуру данных. данные ведь всё-равно нужно через какую-то структуру передать в для запроса сервис гита. Если запрос успешный, не нужно перезаполнять ничего в объекте, мне показалось это оправданным. Переделать?

2022-06-30 07:30 UTC, skvortsovvg commented on app/services/GistQuestionService.rb
> +      if gist.save
переделал, теперь вообще отлично как по мне

2022-06-30 07:34 UTC, skvortsovvg commented on app/services/GistQuestionService.rb
> +    rescue => details
я ошибку перехватывал из тех соображений, что у нас 2 действия - создание gist на гитхаб и создание gist в базе. и чтобы понять на каком именно этапе ошибка, я подумал, что надо их как-то разделить. может же быть проблема при взаимодействии с сайтом или сайт недосутпен. переделал.

2022-06-30 19:13 UTC, BubuntuClu requested changes

2022-06-30 19:13 UTC, BubuntuClu commented on app/models/gist.rb
> +  before_create :create_gist_on_gitgub
нет, так точно делать не надо. надо стараться избегать колбэки, так как они сильно усложняют и путают код. + у тебя гист может быть не создан и придет плохой ответ.

ориентироваться на наличие поля `id` не знаю на сколько оправдано. оно не приходит когда ошибка? 

и ты все таки подменяешь стандартный PK. вот захочешь ты найти запись по ID ты задолбаешься этот ID вводить для поиска в таблице. сделай это лучше отдельным полем все-таки. + индексы для поиска будут работать лучше по инту, чем по строке.

для определения успеха создания используй `last_response` у октокита. там можно посмотреть статус ответа. и этот статус скажет успешно ли прошла операция

2022-07-01 10:04 UTC, skvortsovvg commented on app/models/gist.rb
> +  before_create :create_gist_on_gitgub
Да, если ошибка, id не приходи. Переделал без колбэка, добавил внешний id, добавил проверку через last_response.

2022-07-01 17:42 UTC, BubuntuClu commented on app/models/gist.rb
> +    create_gist_on_gitgub
не могу четко сформулировать свое непринятие такого подхода. что-то в таком подходе мне не нравится, но не могу понять что. из-за этого не могу аргументированно что сказать против него

2022-07-02 07:37 UTC, skvortsovvg commented on app/models/gist.rb
> +    create_gist_on_gitgub
:)

2022-07-04 17:06 UTC, merged