Sql/models
skvortsovvg/TestGuru pull request #2
Opened 2022-04-15 15:48 UTC by skvortsovvg

Решение задания по основам Rails-моделей

2022-04-15 18:40 UTC, VidgarVii requested changes

2022-04-15 18:40 UTC, VidgarVii commented on db/migrate/20220415152016_create_tests.rb
> +
на этом задании надо еще добавить связи м/у таблицами. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```

тут мы укажем, что поле должно быть обязательно заполнен и обеспечим ссылочную целостность данных, через внешний ключ
[внешние ключи](https://en.wikipedia.org/wiki/Foreign_key)


Тест принадлежит Категории и Автору
Тест имеет Вопросы
Вопросы имеют Ответы

Вспомни ДЗ про SQL там уже добавляли эти связи

2022-04-15 18:40 UTC, VidgarVii commented on db/migrate/20220415152146_create_questions.rb
> +      t.integer :test_id
на прошлом ревью я уже писал, что нужны поля со внешними ключами. Нет ключей — нет связей

2022-04-15 18:40 UTC, VidgarVii commented on db/migrate/20220415152940_add_tests_title_null_constraint.rb
> +    change_column_null(:tests, :title, false)
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2022-04-15 18:40 UTC, VidgarVii commented on db/migrate/20220415153957_add_answers_correct_column.rb
> +    add_column(:answers, :correct, :boolean, default: false)
для логических полей рекомендуется запрещать `null`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2022-04-16 11:56 UTC, skvortsovvg commented on db/migrate/20220415152940_add_tests_title_null_constraint.rb
> +    change_column_null(:tests, :title, false)
Понятно, я не против, только в задании так написано, сделать отдельной миграцией

2022-04-16 11:59 UTC, skvortsovvg commented on db/migrate/20220415153957_add_answers_correct_column.rb
> +    add_column(:answers, :correct, :boolean, default: false)
+

2022-04-16 17:28 UTC, VidgarVii requested changes

2022-04-16 17:28 UTC, VidgarVii commented on db/migrate/20220415152016_create_tests.rb
> +      t.string :title
> С помощью механизма миграций, добавьте ограничения целостности на уровне БД в соответствующих таблицах для необходимых атрибутов так, чтобы они **не могли содержать значение NULL**

Это надо сделать для всех полей

2022-04-16 17:28 UTC, VidgarVii commented on db/migrate/20220415152146_create_questions.rb
> +end
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-04-16 17:28 UTC, VidgarVii commented on db/migrate/20220415152940_add_tests_title_null_constraint.rb
> +    change_column_null(:tests, :title, false)
прям ТАК не написано. Я написал как **надо** сделать и **почему** так надо сделать. 
И запомни такую штуку.
100% придерживание ТЗ - признак очень низкой квалификации работника.

2022-04-17 12:30 UTC, VidgarVii requested changes

2022-04-17 12:30 UTC, VidgarVii commented on db/migrate/20220415153957_add_answers_correct_column.rb
> +end
исправил не до конца.
такие миграции с add_column или change_column_default есть смысл создавать только на существующей готовой базе в следующих ПР. А сейчас это лишняя сложность и smell code

2022-04-24 08:06 UTC, merged