Deploy
skvortsovvg/TestGuru pull request #20
Opened 2022-07-18 17:29 UTC by skvortsovvg

2022-07-19 07:17 UTC, BubuntuClu commented on config/routes.rb
> +    get :contact, action: :contact, controller: 'application'
это обычный ресурс и в нем есть два метода `new/create`, не стоит отходить от REST просто так, когда в этом нет надобности

2022-07-19 07:17 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +      ApplicationMailer.new.mail(to: params[:email],
>Добавьте страничку с формой обратной связи. Данные формы должны отправляться на электронную почту администратора

в твоем случае будет отправляться кому-то кого укажут. можно будет с твоего сайта делать рассылку неизвестным людям

2022-07-19 07:17 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +      ApplicationMailer.new.mail(to: params[:email],
нет никакой проверки наличия параметров. зачем слать пустые письма?

2022-07-19 07:27 UTC, skvortsovvg commented on app/controllers/application_controller.rb
> +      ApplicationMailer.new.mail(to: params[:email],
Проверка заполненности полей есть, на самой форме. А по поводу указания адреса, я подумал что такая функция может быть и гостевой, без авторизации. Ок, переделаю.

2022-07-19 08:55 UTC, skvortsovvg commented on config/routes.rb
> +    get :contact, action: :contact, controller: 'application'
Переделал  +

2022-07-19 08:55 UTC, skvortsovvg commented on app/controllers/application_controller.rb
> +      ApplicationMailer.new.mail(to: params[:email],
+

2022-07-19 18:18 UTC, BubuntuClu requested changes

2022-07-19 18:18 UTC, BubuntuClu commented on config/routes.rb
> +    resource :contact, only: [:new, :create], controller: 'contact', path_names: { new: '/', create: '/' }
а что за костыли тут? чем тебя не устраивает `resources :contacts, only: [:new, :create]`?

2022-07-19 18:18 UTC, BubuntuClu commented on app/views/application/contact.html.erb
> +      <%= form.text_field :email, class: "form-control", id: :email, required: true, disabled: true, value: current_user.email, type: "email" %>
наличие `required: true` не является достаточным условием на жесткую валидацию) на бэке тоже должна быть валидация данных. есть хитрые пользователи, которые могут обойти валидацию фронтовую. тогда твое приложение может быть уязвимо. дублировать стоит всегда валидацию фронтовых данных на бэке

2022-07-19 18:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @tests = Test.left_joins(:questions).group(:id).having('COUNT(DISTINCT questions.id) > 0')
этого решения не достаточно. автор добавил первый вопрос и пользовтаель может проходить этот тест. но ответов у вопроса нет. нельзя будет закончить тест. да и автор может задумывал 15 вопросов, а не 1.
надо решить эту проблему глобальней, без подсчетов вопросов/ответов в них

2022-07-19 18:18 UTC, BubuntuClu commented on app/controllers/contact_controller.rb
> +    render 'application/contact'
почему ты рендеришь не `contant/new`? почему вьюха для этого контроллера в другом месте лежит?

2022-07-20 08:07 UTC, skvortsovvg commented on app/controllers/contact_controller.rb
> +    render 'application/contact'
Мне кажется форма обратной связи это часть базового функционала приеложения, зачем выделять в отдельную сущность. Здесь сделал по аналогии со страничкой about, и положил её рядом.

2022-07-20 08:07 UTC, skvortsovvg commented on config/routes.rb
> +    resource :contact, only: [:new, :create], controller: 'contact', path_names: { new: '/', create: '/' }
Мне кажется, что здесь нет необходимости делать /contact/new и contact/create. У нас нет и не будет других функций здесь, поэтому сделал GET и POST просто на адрес /contact. Мне показалось так проще и лучше.

2022-07-20 08:18 UTC, skvortsovvg commented on app/views/application/contact.html.erb
> +      <%= form.text_field :email, class: "form-control", id: :email, required: true, disabled: true, value: current_user.email, type: "email" %>
+

2022-07-20 09:04 UTC, skvortsovvg commented on app/controllers/tests_controller.rb
> +    @tests = Test.left_joins(:questions).group(:id).having('COUNT(DISTINCT questions.id) > 0')
Добавил тестам флажок активации. Если тест не активирован, он не будет отображаться в спике доступных для прохождения тестов.

2022-07-20 17:51 UTC, BubuntuClu commented on app/controllers/contact_controller.rb
> +    render 'application/contact'
страничка about у нас вообще была статичной страницой и ее не должно быть в роутах.
любой функционал приложения - стоит выносить в отдельные сущности, чтобы не было скопления "мусора" в одном месте. лучше придерживаться формата расположения файлов заданных фреймворком, так как это ожидаемое поведение, и то что ты переопределяешь его может вводить в ступор.

2022-07-20 17:53 UTC, BubuntuClu commented on config/routes.rb
> +    resource :contact, only: [:new, :create], controller: 'contact', path_names: { new: '/', create: '/' }
а какая разница будут ли еще други экшены? ты наперед никогда не сможешь прегудать как будет развиваться приложение и каждый раз костылять под текущее решение код, вместо обычной реализции, которая не потребует потом перепила функциональности при его расширении, такое себе решение.

+ базовый REST никто не отменял, ожидаешь опредленного правила формирования url

2022-07-20 17:56 UTC, BubuntuClu commented on app/controllers/contact_controller.rb
> +    if params[:message] then
`then` не пишется в рубях

2022-07-20 17:56 UTC, BubuntuClu commented on app/controllers/contact_controller.rb
> +      redirect_to :new,  alert: 'Пустое сообщение, напишите что-нибудь'
`end` потерял

2022-07-20 17:56 UTC, BubuntuClu commented on app/models/test.rb
> +    errors.add(:Test, ": to activate it has to include at least one question!") if questions.count == 0
ну, это сомнительная проверка на самом деле. она логически ничего не дает. ну есть один вопрос, почему на этом основании делается вывод о том что можно публиковать? вопрос без ответа не имеет смысла, а ты тут это не проверяешь

2022-07-20 17:56 UTC, BubuntuClu commented on app/models/test.rb
> +    errors.add(:Test, ": to activate it has to include at least one question!") if questions.count == 0
и похоже эта проверка заставляет тебя писать костыль по вьюхе. что возможность сделать тест готовый можно при редактировании, а не при создании

2022-07-21 06:44 UTC, skvortsovvg commented on app/models/test.rb
> +    errors.add(:Test, ": to activate it has to include at least one question!") if questions.count == 0
Вопрос без ответа не имеет конечно смысла, но и не приводит к ошибке теперь. Изначально эту проблему решал (т.к. замечание было, что приложение падало, если в тесте нет вопросов). Из комментария понимаю, что сделал не оптимально, но не понятно как было бы правильно это реализовать.

2022-07-21 16:07 UTC, merged