badges
skvortsovvg/TestGuru pull request #21
Opened 2022-07-26 07:58 UTC by skvortsovvg

2022-07-26 18:22 UTC, BubuntuClu requested changes

2022-07-26 18:22 UTC, BubuntuClu commented on app/controllers/admin/reward_rules_controller.rb
> +    params.require(:reward_rule).permit(:title, :leftValue, :comparsion, :rightValue, :additional)
leftValue/rightValue - в руби испольузем snake_case

2022-07-26 18:22 UTC, BubuntuClu commented on app/models/badge.rb
> +  def self.check_rewards(result, current_user)
логикой должен заниматься отдельный сервис, это не задача модели уметь себя выдавать

2022-07-26 18:22 UTC, BubuntuClu commented on app/models/result.rb
>    def accept!(answer_id)
этот метод только ответы принимает.
размести логику выставления результата/успеха в другом месте

2022-07-26 18:22 UTC, BubuntuClu commented on config/routes.rb
> +      resources :badges do
do/end выглядит лишним

2022-07-26 18:22 UTC, BubuntuClu commented on db/migrate/20220721161041_create_reward_rules.rb
> +      t.string :leftValue
snake_case.

а зачем хранить левое и правое значение какое-то?
почему бы не хранить имя правила, и аттрибут для правила. правило же будет работать по одному сценарию. допустим все тесты категории. параметр - категория. а какой второй параметр может потребоваться? так же и с уровнем.

для прохождения с первого раза параметр даже и не нужен.

2022-07-26 18:22 UTC, BubuntuClu commented on db/seeds.rb
> +new_test = Test.create(title: "Node.js", level: 3, category_id: 1, author_id: 2, is_active: true)
нельзя хардкодить id в сидах, на объекты переделай

2022-07-26 18:22 UTC, BubuntuClu commented on db/seeds.rb
> +                                       leftValue: "current_user.results.where(test: result.test).count",
то что ты написал про безопасность, это правильно. нельзя позволять такое вводить. даже то что права имеет админ, не значит что его не взломают или он сам не накосячит.

более простая реализация должна быть.

такую реализацию один раз пытались сделать, но там было на js возможность выбора из представленных компонентов, насобирать выражение для проверки. руками нельзя было ничего прописывать

2022-07-26 18:22 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :passed_with_category, -> (category) { connection.select_one("SELECT
скоуп должен возвращать объект ActiveRecord::Relation

2022-07-26 18:22 UTC, BubuntuClu commented on app/models/user.rb
> +  scope :passed_with_level, ->(level) { results.joins(:test).where('tests.level = :level', level: level).count(:test_id) }
count нельзя помещать в скоуп

2022-07-27 08:23 UTC, skvortsovvg commented on app/models/user.rb
> +  scope :passed_with_category, -> (category) { connection.select_one("SELECT
это лишние, я изначально подумал сделать через скоупы, убрал +

2022-07-27 08:23 UTC, skvortsovvg commented on app/models/user.rb
> +  scope :passed_with_level, ->(level) { results.joins(:test).where('tests.level = :level', level: level).count(:test_id) }
+

2022-07-27 08:25 UTC, skvortsovvg commented on config/routes.rb
> +      resources :badges do
+

2022-07-27 08:28 UTC, skvortsovvg commented on db/seeds.rb
> +new_test = Test.create(title: "Node.js", level: 3, category_id: 1, author_id: 2, is_active: true)
+

2022-07-27 08:31 UTC, skvortsovvg commented on app/controllers/admin/reward_rules_controller.rb
> +    params.require(:reward_rule).permit(:title, :leftValue, :comparsion, :rightValue, :additional)
+

2022-07-27 08:33 UTC, skvortsovvg commented on app/models/badge.rb
> +  def self.check_rewards(result, current_user)
+

2022-07-27 08:41 UTC, skvortsovvg commented on app/models/result.rb
>    def accept!(answer_id)
+

2022-07-27 08:47 UTC, skvortsovvg commented on db/migrate/20220721161041_create_reward_rules.rb
> +      t.string :leftValue
если брать какие-то примитивные условия, то да. но если взять более сложные условия, то такая реализация дает возможность сконстуировать практически любые правила. это же плюс в данном случае

2022-07-27 08:48 UTC, skvortsovvg commented on db/migrate/20220721161041_create_reward_rules.rb
> +      t.string :leftValue
поправил snake_case

2022-07-27 08:54 UTC, skvortsovvg commented on db/seeds.rb
> +                                       leftValue: "current_user.results.where(test: result.test).count",
ну да, я понимаю, я сразу сдела сноску про то, что реализация небезопасная. но ведь интересная, можно сконструировать много интересных правил и сколько угодно бейджей, без всякого хардкодинга. акцент делал имеено на этом, это же всего лишь курсовой проект, почему бы не поэкспериментировать?

2022-07-27 17:22 UTC, BubuntuClu commented on app/models/result.rb
> +    self.score = result
и тут этого не должно быть. каждый метод, должен делать что-то одно. иначе это ниндзя метод. вот вызываешь ты метод, думаешь что он просто что-то делает со след вопросом, а под капотом еще кучу всего выполняет. не делай так

2022-07-28 08:54 UTC, skvortsovvg commented on app/models/result.rb
> +    self.score = result
вроде понял, переделаю в следующем задании

2022-07-28 08:56 UTC, merged