Activerecord 1
skvortsovvg/TestGuru pull request #3
Opened 2022-04-20 13:30 UTC by skvortsovvg

2022-04-20 13:40 UTC, BubuntuClu commented on app/models/test.rb
> +    self.select(:title).where("title LIKE :param", param: "%#{str}%" ).order('title DESC').pluck('title')
1 - `select` тут не нужен, так как ты используешь `pluck`.
2 - тебе параметром приходит название категории, а не название теста

2022-04-20 13:40 UTC, BubuntuClu commented on db/seeds.rb
> +new_test = Test.create(title: "Ruby", level: 2, category_id: category.id, author_id: User.first.id)
положи созданного пользователя в переменную на 10ой строке, и используй его вместо `User.first.id`

2022-04-20 13:40 UTC, BubuntuClu commented on db/seeds.rb
> +new_test = Test.create(title: "Ruby", level: 2, category_id: category.id, author_id: User.first.id)
и везде где дальше потребуется пользователь используй эту переменную, а не делай лишний запрос в БД

2022-04-20 15:40 UTC, skvortsovvg commented on app/models/test.rb
> +    self.select(:title).where("title LIKE :param", param: "%#{str}%" ).order('title DESC').pluck('title')
На счет pluck  я понял, исправил. А вот на счет параметра и категории - непонятно.

2022-04-20 15:40 UTC, skvortsovvg commented on db/seeds.rb
> +new_test = Test.create(title: "Ruby", level: 2, category_id: category.id, author_id: User.first.id)
Ок, поправлю

2022-04-20 16:50 UTC, BubuntuClu requested changes

2022-04-20 16:50 UTC, BubuntuClu commented on db/seeds.rb
> +Result.create(user_id: User.first.id, test_id: new_test.id)
не все заменил

2022-04-20 16:50 UTC, BubuntuClu commented on app/models/test.rb
> +    self.where("title LIKE :param", param: "%#{str}%").order('title DESC').pluck(:title)
из задания "название категории передается в метод в качестве аргумента"
сейчас ты фильтруешь по названию теста, а не по названию категории

2022-04-20 16:51 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins("inner join results on tests.id = results.test_id").where("results.user_id = :user_id and (tests.level = :level or :level is null)", user_id: self.id, level: level).distinct.pluck
плак тут не нужен, тут надо возвращать коллекцию объектов

2022-04-20 17:11 UTC, skvortsovvg commented on app/models/user.rb
> +    Test.joins("inner join results on tests.id = results.test_id").where("results.user_id = :user_id and (tests.level = :level or :level is null)", user_id: self.id, level: level).distinct.pluck
+

2022-04-20 17:11 UTC, skvortsovvg commented on app/models/test.rb
> +    self.where("title LIKE :param", param: "%#{str}%").order('title DESC').pluck(:title)
+

2022-04-20 17:11 UTC, skvortsovvg commented on db/seeds.rb
> +Result.create(user_id: User.first.id, test_id: new_test.id)
+

2022-04-21 07:16 UTC, BubuntuClu approved these changes

2022-04-24 08:07 UTC, merged