Activerecord 2
skvortsovvg/TestGuru pull request #4
Opened 2022-04-22 09:18 UTC by skvortsovvg

2022-04-22 16:45 UTC, BubuntuClu requested changes

2022-04-22 16:45 UTC, BubuntuClu commented on app/models/test.rb
>      self.joins('join categories on tests.category_id = categories.id').where('categories.title like :str', str: "%#{str}%").order('title DESC')
ты теперь можешь отрефакторить запросы с использованием ассоциаций

2022-04-22 16:45 UTC, BubuntuClu commented on app/models/user.rb
> +
добавь еще ассоциацию созданных тестов пользователем

2022-04-22 16:45 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: "User"
в ПРе нет миграции на добавление поля в таблицу, для реализации это ассоциации

2022-04-22 18:00 UTC, skvortsovvg commented on app/models/test.rb
> +  belongs_to :author, class_name: "User"
не понял, какого поля? все поля есть ещё с прошлого задания, зачем здесь дополнительные миграции?

2022-04-23 13:29 UTC, skvortsovvg commented on app/models/user.rb
> +
+

2022-04-23 13:30 UTC, skvortsovvg commented on app/models/test.rb
>      self.joins('join categories on tests.category_id = categories.id').where('categories.title like :str', str: "%#{str}%").order('title DESC')
+

2022-04-23 19:15 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: "User"
не заметил что ты сделал поля в прошлом уроке

2022-04-24 18:33 UTC, BubuntuClu commented on app/models/user.rb
>      # select DISTINCT tests.title from results inner join tests on tests.id = results.test_id and results.user_id = 1 and tests.level = 1;
удали весь не нужный код, не стоит захламлять репозиторий комментами не нужного кода. старый код ты всегда можешь через историю посмотреть

2022-04-24 18:33 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins(:results).where("results.user_id = :user_id and (tests.level = :level or :level is null)", user_id: self.id, level: level).distinct
все это можно сократить до 
```
def my_tests(level = nil)
  tests.where(level: level)
end
```

2022-04-25 10:20 UTC, skvortsovvg commented on app/models/user.rb
> +    Test.joins(:results).where("results.user_id = :user_id and (tests.level = :level or :level is null)", user_id: self.id, level: level).distinct
Если сделать именно так, то запрос вернется пустой, если не указать уровень, а я хотел чтобы тогда возвращались все тесты пользователя. Но мысль я понял, поправил.

2022-04-25 10:21 UTC, skvortsovvg commented on app/models/user.rb
>      # select DISTINCT tests.title from results inner join tests on tests.id = results.test_id and results.user_id = 1 and tests.level = 1;
+

2022-04-25 10:21 UTC, merged