Activerecord 3. Scopes & validations
skvortsovvg/TestGuru pull request #9
Opened 2022-05-01 07:21 UTC by skvortsovvg

2022-05-01 18:30 UTC, BubuntuClu requested changes

2022-05-01 18:30 UTC, BubuntuClu commented on app/models/question.rb
> +    errors.add(:Question, "must has from 1 to 4 answers") if !(1..4).include?(answers.count)
1 - при сохранении ответа не будет вызываться валидация ответа. нужно перенести в другой класс валидацию
2 - question.answers.count > 4

2022-05-01 18:30 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :find_by_title, -> (str) { joins(:category).where('categories.title like :str', str: "%#{str}%").order('title DESC') }
1 - в этом скоупе теперь никак не учитывается пользователь. скоуп не равносилен методу. и вроде по условия прошлых заданий должен быть выбор только названий тестов через pluck
2 - сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2022-05-01 18:30 UTC, BubuntuClu commented on db/schema.rb
> +    t.string "email", default: "", null: false
дефолтное значение для почты не стоит ставить никогда. если пользователь не ввел, то должна быть ошибка что пустое значение, а не ставится дефолт. плюс если будет уникальность почт, то второе дефолтное значение будет ошибку вызывать

2022-05-01 18:30 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true,
>Может существовать только один Тест с данным названием и уровнем

уникальнй должна быть связка тайтл+левел, а не только тайтл.

так же надо добавить уникальный составной индекс в БД

2022-05-03 11:44 UTC, skvortsovvg commented on db/schema.rb
> +    t.string "email", default: "", null: false
+

2022-05-03 11:44 UTC, skvortsovvg commented on app/models/test.rb
> +  validates :title, presence: true,
+

2022-05-03 11:44 UTC, skvortsovvg commented on app/models/test.rb
> +  scope :find_by_title, -> (str) { joins(:category).where('categories.title like :str', str: "%#{str}%").order('title DESC') }
+

2022-05-03 11:44 UTC, skvortsovvg commented on app/models/question.rb
> +    errors.add(:Question, "must has from 1 to 4 answers") if !(1..4).include?(answers.count)
+

2022-05-04 09:15 UTC, merged